# Import libraries.

In [57]:
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

# First read all the data from URL

In [71]:
import urllib
from urllib.request import urlretrieve
import pandas as pd

url = 'http://lib.stat.cmu.edu/datasets/boston'
urlretrieve(url, 'boston.txt')

data = []
with open('boston.txt', 'r') as file:
    for line in file:
        row = line.split()
        if len(data) == 0:
            data.append(row[:14])
        elif len(data[-1]) < 14:
            data[-1].extend(row[:14-len(data[-1])])
        else:
            data.append(row[:14])

df_web = pd.DataFrame(data, columns=['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV'])
print(df_web.shape)
df_web.head(25)

(515, 14)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,The,Boston,house-price,data,of,"Harrison,",D.,and,"Rubinfeld,",D.L.,'Hedonic,prices,and,the
1,"vol.5,","81-102,",1978.,Used,in,"Belsley,",Kuh,&,"Welsch,",'Regression,diagnostics,"...',","Wiley,",1980.
2,pages,244-261,of,the,latter.,Variables,in,order:,CRIM,per,capita,crime,rate,by
3,ZN,proportion,of,residential,land,zoned,for,lots,over,"25,000",sq.ft.,INDUS,proportion,of
4,CHAS,Charles,River,dummy,variable,(=,1,if,tract,bounds,river;,0,otherwise),NOX
5,RM,average,number,of,rooms,per,dwelling,AGE,proportion,of,owner-occupied,units,built,prior
6,DIS,weighted,distances,to,five,Boston,employment,centres,RAD,index,of,accessibility,to,radial
7,TAX,full-value,property-tax,rate,per,"$10,000",PTRATIO,pupil-teacher,ratio,by,town,B,1000(Bk,-
8,LSTAT,%,lower,status,of,the,population,MEDV,Median,value,of,owner-occupied,homes,in
9,0.00632,18.00,2.310,0,0.5380,6.5750,65.20,4.0900,1,296.0,15.30,396.90,4.98,24.00
10,0.02731,0.00,7.070,0,0.4690,6.4210,78.90,4.9671,2,242.0,17.80,396.90,9.14,21.60
11,0.02729,0.00,7.070,0,0.4690,7.1850,61.10,4.9671,2,242.0,17.80,392.83,4.03,34.70
12,0.03237,0.00,2.180,0,0.4580,6.9980,45.80,6.0622,3,222.0,18.70,394.63,2.94,33.40
13,0.06905,0.00,2.180,0,0.4580,7.1470,54.20,6.0622,3,222.0,18.70,396.90,5.33,36.20
14,0.02985,0.00,2.180,0,0.4580,6.4300,58.70,6.0622,3,222.0,18.70,394.12,5.21,28.70
15,0.08829,12.50,7.870,0,0.5240,6.0120,66.60,5.5605,5,311.0,15.20,395.60,12.43,22.90
16,0.14455,12.50,7.870,0,0.5240,6.1720,96.10,5.9505,5,311.0,15.20,396.90,19.15,27.10
17,0.21124,12.50,7.870,0,0.5240,5.6310,100.00,6.0821,5,311.0,15.20,386.63,29.93,16.50
18,0.17004,12.50,7.870,0,0.5240,6.0040,85.90,6.5921,5,311.0,15.20,386.71,17.10,18.90
19,0.22489,12.50,7.870,0,0.5240,6.3770,94.30,6.3467,5,311.0,15.20,392.52,20.45,15.00
20,0.11747,12.50,7.870,0,0.5240,6.0090,82.90,6.2267,5,311.0,15.20,396.90,13.27,18.90
21,0.09378,12.50,7.870,0,0.5240,5.8890,39.00,5.4509,5,311.0,15.20,390.50,15.71,21.70
22,0.62976,0.00,8.140,0,0.5380,5.9490,61.80,4.7075,4,307.0,21.00,396.90,8.26,20.40
23,0.63796,0.00,8.140,0,0.5380,6.0960,84.50,4.4619,4,307.0,21.00,380.02,10.26,18.20
24,0.62739,0.00,8.140,0,0.5380,5.8340,56.50,4.4986,4,307.0,21.00,395.62,8.47,19.90

## Since the above dataframe has 9 rows that is not data, let's delete those rows and create a new dataframe called "boston_housing"

In [65]:
# Create a new DataFrame with rows 9 to the end of table-1
boston_housing = df_web.iloc[9:, :].reset_index(drop=True)

# Print the shape of the new DataFrame
boston_housing

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.00,2.310,0,0.5380,6.5750,65.20,4.0900,1,296.0,15.30,396.90,4.98,24.00
1,0.02731,0.00,7.070,0,0.4690,6.4210,78.90,4.9671,2,242.0,17.80,396.90,9.14,21.60
2,0.02729,0.00,7.070,0,0.4690,7.1850,61.10,4.9671,2,242.0,17.80,392.83,4.03,34.70
3,0.03237,0.00,2.180,0,0.4580,6.9980,45.80,6.0622,3,222.0,18.70,394.63,2.94,33.40
4,0.06905,0.00,2.180,0,0.4580,7.1470,54.20,6.0622,3,222.0,18.70,396.90,5.33,36.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.00,11.930,0,0.5730,6.5930,69.10,2.4786,1,273.0,21.00,391.99,9.67,22.40
502,0.04527,0.00,11.930,0,0.5730,6.1200,76.70,2.2875,1,273.0,21.00,396.90,9.08,20.60
503,0.06076,0.00,11.930,0,0.5730,6.9760,91.00,2.1675,1,273.0,21.00,396.90,5.64,23.90
504,0.10959,0.00,11.930,0,0.5730,6.7940,89.30,2.3889,1,273.0,21.00,393.45,6.48,22.00
505,0.04741,0.00,11.930,0,0.5730,6.0300,80.80,2.5050,1,273.0,21.00,396.90,7.88,11.90